# docker-compose.staging.yml
# Staging environment docker compose file

services:
  certbot:
    container_name: stagehunter-certbot
    image: certbot/certbot:v3.0.1
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      nginx:
        condition: service_started

  nginx:
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  frontend:
    build:
      target: staging
    # No volumes needed for staging
    volumes: []

  backend: {}

  db:
    # No ports needed for staging
    ports: []
