# docker-compose.yml
# Required environment variables:
# TARGET - The target environment to build the frontend for
#   (development, production)

services:
  nginx:
    container_name: stagehunter-nginx
    image: nginx:1.27.2
    ports:
      - 80:80
    networks:
      - frontend-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: stagehunter-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET}
    volumes:
      - ./frontend:/app
      - /app/.next
      - /app/node_modules
    networks:
      - frontend-network
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
    restart: unless-stopped
    depends_on:
      - backend
      - db

  backend:
    container_name: stagehunter-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    networks:
      - frontend-network
      - backend-network
    volumes:
      - ./backend/.pgpass:/root/.pgpass
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: stagehunter-db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    restart: unless-stopped
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password

volumes:
  pgdata:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

secrets:
  pg_password:
    file: ./db/.pg_password
