services:
  frontend:
    container_name: stagehunter-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend-network
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
    restart: unless-stopped
    depends_on:
      - backend
      - db

  backend:
    container_name: stagehunter-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped
    volumes:
      - ./backend/.pgpass:/root/.pgpass
    depends_on:
      - db

  db:
    container_name: stagehunter-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    restart: unless-stopped
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password

volumes:
  pgdata:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

secrets:
  pg_password:
    file: ./db/.pg_password
