# docker-compose.staging.yml
# Staging environment docker compose file

services:
  nginx:
    build:
      target: staging

  frontend:
    build:
      target: staging
    # No volumes needed for staging
    volumes: []

  backend:
    # No ports needed for staging
    ports: []

  db:
    # No ports needed for staging
    ports: []
