services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - frontend-network
    restart: unless-stopped
    volumes:
      - ~/.pgpass:/root/.pgpass

networks:
  frontend-network:
    driver: bridge
